# Generated by Django 3.2.6 on 2021-09-12 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
