# Generated by Django 3.2.6 on 2021-09-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_issue_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='issue_date',
            new_name='date_created',
        ),
    ]
