# Generated by Django 3.2.6 on 2021-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'No Priority'), (1, 'Low'), (2, 'Moderate'), (3, 'High'), (4, 'Extreme')], default=0),
        ),
    ]
