# Generated by Django 3.2.6 on 2021-09-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_response_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'No Priority'), (1, 'Low'), (2, 'Moderate'), (3, 'High'), (4, 'Extreme')], default=0, help_text='Priority will auto set to "No Priority" if Response is NOT postive.<br/>Priority will auto set to "Moderate" if Response is postive and Priority is "No Priority".'),
        ),
    ]
