# Generated by Django 3.2.6 on 2021-09-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_alter_response_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='common_for_all',
        ),
    ]
