# Generated by Django 3.2.6 on 2021-09-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_remove_tweet_common_for_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='common_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
