# Generated by Django 4.0 on 2021-12-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_tweet_common_for_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='common_for_all',
        ),
    ]
